### PR TITLE
Improve UI styling for about page

### PR DESCRIPTION
**Pull request by nitishragu12**

### CODE REVIEW

**Review by somni1oquist — COMMENTED** [review]
Check the design, probably need to replace images and change the tone based on later color theme?
#129 will decide the final tone of our app by @maxtse25

**Comment by nitishragu12** [comment]
Added new styles for the page

- The background image is now full screen
- Names have been centered inside the box
- Project roles have been specified under the names as tags

Waiting for the final UI styling of the app to further change the theme

**Comment by somni1oquist** [comment]
Not able to scroll to the bottom. Do you have same issue? @nitishragu12 @maxtse25 
Screenshot 2024-10-06 at 21 18 22

**Comment by maxtse25** [comment]
> Not able to scroll to the bottom. Do you have same issue? @nitishragu12 @maxtse25 Screenshot 2024-10-06 at 21 18 22

I will try to fix it in my commit.

**Review by maxtse25 — APPROVED** [review]
Thanks for the work

**Pull request merged**
